name: AltDetector
main: com.bobcat00.altdetector.AltDetector
version: ${project.version}
author: Bobcat00
description: Detects possible alt accounts
api-version: 1.13
softdepend: [PremiumVanish, SuperVanish]
commands:
  alt:
    description: Lists possible alt accounts of player.
    permission: altdetector.alt
    usage: "/alt [player]"
permissions:
  altdetector.alt:
    description: Allows use of the /alt command
    default: op
  altdetector.alt.delete:
    description: Allows use of the /alt delete command
    default: op
  altdetector.alt.seevanished:
    description: Allows this player to use /alt command to see vanished players
    default: op
  altdetector.exempt:
    description: Exempts player from data being saved and a lookup being done when joining the server
    default: false
  altdetector.notify:
    description: Notifies this player when an alt is detected
    default: op
  altdetector.notify.seevanished:
    description: Notifies this player when an alt is detected for a vanished player
    default: op
